language: node_js
node_js:
- node
branches:
  only:
  - master
script:
- 
deploy:
  provider: firebase
env:
  global:
    secure: JgSyJbnlWqNFZkyBLNvC43tLQeYCYoCw3aCVFKCyWm2uaAAz7aSZHKI91Lk1OUnRILmWKlAsZ0BmRp5Y96eFH8h5uF071mQGBN+eUFr9Mmjcc0MsW6aRzezylSEG/ebSjlSdkyyenmRJ9D4csfu0J9m7umLEJx1n7RBF8NbJvaDFyhzQI0fdp5qpRkenzhg0VG1HvG2g6vtO7l3eiQrQcxZn5QA62VTD3BqVlD18RYIcPOjC6ptddu/aEhjO26dIY2beKBJEtQlJxFvtyGA4rg5ytHaiQqqffQb3smyWyy6pH6x8WcXxEd/NgdiiDoCkn5yJN5A6SFSvU98Qhvwc3MU+Hi+k72obL9Xb4d0iHgdh6M4VhD7zL3r32vQ0iew2e4/bV6OGOApLLlgSM6klkkh7HfEyZ3bxw+fmt+9+MlMW8fi9ZeXq8IUNeA5HPWOoVoUoMqD8P5ESj8F1fgdjl5XKobRDIek78trmSSLB1jDJVDHt1eqhmnS2xlst6ZXvk17BjrVHPaFy1ydvyLHF9BzQo98KJDm/i/JAiDAsgbGF779ABCRz8IJf5uJyQziLOThThpCSuOKxPK1/SdcZy3vK4oMVA9OFyBw01BKyK8dLNRiWCcczcrr8iVjsmlTPK5vOZL4x9ZToYcLlUdJ+KZYDi+prJlj6K+aqgeFwhIg=
